### ISSUE TITLE
Tesselation of larger urban areas

### ISSUE THREAD

**Issue by damian-romero** [martinfleis/momepy#123]
*I was unable to perform a tesselation from larger urban areas, often exiting with different error messages (small towns always worked like a charm).*

## requirements
- anaconda3
- python3.8
- geopandas==0.6.2
- matplotlib==3.1.2 
- osmnx==0.10 

```
import momepy
import geopandas as gpd
import matplotlib.pyplot as plt
import osmnx as ox

# Get data from open street maps (they all fail, see below for error messages)
#gdf = ox.footprints.footprints_from_place(place='Vancouver, Canada')
#gdf = ox.footprints.footprints_from_place(place='Mexico City, CDMX, Mexico')
gdf = ox.footprints.footprints_from_place(place='Paris, France')

gdf_projected = ox.project_gdf(gdf)

# Preprocess building data
buildings = momepy.preprocess(gdf_projected, size=30,
                              compactness=True, islands=True)

buildings['uID'] = momepy.unique_id(buildings)
limit = momepy.buffered_limit(buildings)

tessellation = momepy.Tessellation(buildings, unique_id='uID', limit=limit)
tessellation_gdf = tessellation.tessellation

# plot
f, ax = plt.subplots(figsize=(10, 10))
tessellation_gdf.plot(ax=ax)
buildings.plot(ax=ax, color='white, alpha=.5)
ax.set_axis_off()
plt.show()
```

### 'Vancouver, Canada'

```
Traceback (most recent call last):
  File "momepy_dr.py", line 21, in <module>
    buildings = momepy.preprocess(gdf_projected, size=30,
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/momepy/utils.py", line 406, in preprocess
    blg = blg.explode()
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/geopandas/geodataframe.py", line 695, in explode
    df = pd.concat(
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 258, in concat
    return op.get_result()
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 472, in get_result
    new_data = concatenate_block_managers(
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 2059, in concatenate_block_managers
    return BlockManager(blocks, axes)
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 143, in __init__
    self._verify_integrity()
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 345, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1718, in construction_error
    raise ValueError(
ValueError: Shape of passed values is (132850, 183), indices imply (132842, 183)
```

### 'Mexico City, CDMX, Mexico'

```
Traceback (most recent call last):
  File "momepy_dr.py", line 9, in <module>
    gdf = ox.footprints.footprints_from_place(place='Mexico City, CDMX, Mexico')
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/osmnx/footprints.py", line 359, in footprints_from_place
    return create_footprints_gdf(polygon, retain_invalid=retain_invalid,
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/osmnx/footprints.py", line 171, in create_footprints_gdf
    responses = osm_footprints_download(polygon, north, south, east, west, footprint_type)
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/osmnx/footprints.py", line 121, in osm_footprints_download
    geometry_proj_consolidated_subdivided = consolidate_subdivide_geometry(geometry_proj, max_query_area_size=max_query_area_size)
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/osmnx/core.py", line 736, in consolidate_subdivide_geometry
    raise TypeError('Geometry must be a shapely Polygon or MultiPolygon')
TypeError: Geometry must be a shapely Polygon or MultiPolygon
(testEnv) Damians-MacBook-Pro:Code Bits ...$ python momepy_dr.py 
Traceback (most recent call last):
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'geometry'
```

### 'Paris, France'
```
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 2.3679365970466395 48.863773911496658 at 2.3679365970466395 48.863773911496658
Traceback (most recent call last):
  File "momepy_dr.py", line 10, in <module>
    gdf = ox.footprints.footprints_from_place(place='Paris, France')
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/osmnx/footprints.py", line 359, in footprints_from_place
    return create_footprints_gdf(polygon, retain_invalid=retain_invalid,
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/osmnx/footprints.py", line 228, in create_footprints_gdf
    temp_poly=temp_poly.difference(footprints[inner_poly]['geometry'])
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/shapely/geometry/base.py", line 616, in difference
    return geom_factory(self.impl['difference'](self, other))
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/shapely/topology.py", line 70, in __call__
    self._check_topology(err, this, other)
  File "/Users/.../anaconda3/envs/testEnv/lib/python3.8/site-packages/shapely/topology.py", line 35, in _check_topology
    raise TopologicalError(
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x1533ee310>
```

**Comment by martinfleis** [comment]
Hi @damian-romero,

thanks for the report. From traceback it seems that Mexico and Paris both failed at `ox.footprints.footprints_from_place`, which means that even before momepy could have done anything. It might be worth checking OSMnx issues if that happened before (I assume so). 

Vancouver fails on `momepy.preprocess`, but during the very first step of it, which is `.explode()`, so I'll take that to GeoPandas as it is issue which should be resolved there.

https://github.com/martinfleis/momepy/blob/12e5703fd96b709d1186307bcc396887d2704924/momepy/utils.py#L405-L406

One more thing to keep in mind when working with large areas, especially using `Tessellation`. It discretise the shape of each building into set of points, with default segment distance between them of 0.5m. Which means that you'll end up with a LOT of points at one point and often run out of memory. So working with large areas you need to be aware of this issue and either change default `segment` to larger distance, do it bit by bit, or have a powerful machine.

If you do it bit by bit, keep some overlap and them while merging bits together keep only smaller features (of the same unique ID).

As there is nothing I can do in momepy to fix these errors, I'll close this issue. I'll move the Vancouver issue to correct place.

Thanks!

**Comment by martinfleis** [comment]
Hi @damian-romero,

possible workaround for Vancouver is to reset index before doing `preprocess`.

```
gdf_projected = ox.project_gdf(gdf)

# Preprocess building data
gdf_projected = gdf_projected.reset_index(drop=True)
buildings = momepy.preprocess(gdf_projected, size=30,
                              compactness=True, islands=True)
```

**Comment by damian-romero** [comment]
@martinfleis the index reset works perfectly. It did take a while as you suggested one does need a good machine. It makes sense that you were working on AWS for your 2020 paper. I will go ahead and update my blog entry.

Thank you!
